### ISSUE TITLE
Failed to run "Set RVM" menu

### ISSUE THREAD

**Issue by infininight** [textmate/ruby-on-rails-tmbundle#8]
I have a RoR project, and I clicked on "Set RVM" menu in the bundle.

The first error was rvm.rb unable to load 'rails_bundle_tools'

After I fixed it (I added a correct include path to top of rvm/rvm.rb, I get a following error:

```

/Users/hron/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/lib/rvm/rvm.rb:46:in `version': private method `gsub' called for nil:NilClass (NoMethodError)
    from /Users/hron/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/lib/rvm/rvm.rb:57:in `formatted_message'
    from /Users/hron/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/lib/rvm/rvm.rb:17:in `choose!'
    from /Users/hron/Library/Application Support/TextMate/Managed/Bundles/Ruby on Rails.tmbundle/Support/lib/rvm/rvm.rb:84
```

---

_Moved from old textmate repository, original report from @hron84_

**Comment by flyweights** [comment]
![image](https://user-images.githubusercontent.com/12111609/56452733-8e330380-6367-11e9-956e-d203047bf5d3.png)

**Comment by hron84** [comment]
Sorry guys the solution came too late. I no longer have an OS X capable computer. Anyway, thanks for the effort.
